/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengelolaanbuku;

/**
 *
 * @author LENOVO
 */
import java.awt.HeadlessException;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import pengelolaanbuku.koneksi;
import javax.swing.table.*;

public class interfacebuku extends javax.swing.JFrame {

    /**
     * Creates new form interfacebuku
     */
    
    Connection koneksi = pengelolaanbuku.koneksi.getKoneksi();
    Statement tokobuku; 
    ResultSet databuku; 
    Boolean ketemu = false;
    
    public interfacebuku() {
        initComponents();
    }
    
    //mengkosongkan setelah diInput
    private void kosong() {
        inputjudul.setText("");
        inputpenulis.setText("");
        inputharga.setText("");
        inputstok.setText("");

        buttontambah.setText("Simpan");
//        btnEdit.setEnabled(false);
    }
    
    public void Tampilkanbuku() {
        try {
            tokobuku = koneksi.createStatement();
            databuku = tokobuku.executeQuery("SELECT * FROM data_buku");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Judul");
            model.addColumn("Penulis");
            model.addColumn("Harga");
            model.addColumn("Stok");

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            while (databuku.next()) {
                Object[] data = {
                    databuku.getString("judul"),
                    databuku.getString("penulis"),
                    databuku.getString("harga"),
                    databuku.getString("stok"),
                };
                model.addRow(data);
                tabelbuku.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada Kesalahan " + e.getMessage());
        }
    }

    private void Caribuku() {
        try {
            tokobuku = koneksi.createStatement();
            databuku = tokobuku.executeQuery("SELECT * FROM data_buku WHERE judul LIKE '%" + textcari.getText() + "% '||"
                    + "penulis LIKE '%" + textcari.getText() + "%' ||  "
                    + "harga LIKE '%" + textcari.getText() + "%' || "
                    + "stok LIKE '%" + textcari.getText() + "%'");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Judul");
            model.addColumn("Penulis");
            model.addColumn("Harga");
            model.addColumn("Stok");

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            while (databuku.next()) {
                Object[] data = {
                    databuku.getString("judul"),
                    databuku.getString("penulis"),
                    databuku.getString("harga"),
                    databuku.getString("stok"),
                };
                model.addRow(data);
                tabelbuku.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada Kesalahan " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbuku = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputjudul = new javax.swing.JTextField();
        inputharga = new javax.swing.JTextField();
        inputpenulis = new javax.swing.JTextField();
        inputstok = new javax.swing.JTextField();
        buttontambah = new javax.swing.JButton();
        textcari = new javax.swing.JTextField();
        buttonhapus = new javax.swing.JButton();
        buttonbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DAFTAR BUKU");

        tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul", "Penulis", "Harga", "Stok"
            }
        ));
        tabelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbuku);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Judul");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Penulis");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Stok");

        inputjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputjudulActionPerformed(evt);
            }
        });

        inputharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputhargaActionPerformed(evt);
            }
        });

        inputpenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpenulisActionPerformed(evt);
            }
        });

        inputstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputstokActionPerformed(evt);
            }
        });

        buttontambah.setText("Tambah");
        buttontambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontambahActionPerformed(evt);
            }
        });

        textcari.setToolTipText("");
        textcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcariActionPerformed(evt);
            }
        });
        textcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textcariKeyPressed(evt);
            }
        });

        buttonhapus.setText("Hapus");
        buttonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhapusActionPerformed(evt);
            }
        });

        buttonbatal.setText("Batal");
        buttonbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputstok, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputharga)
                                    .addComponent(inputpenulis, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttontambah)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonbatal))
                                            .addComponent(inputjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textcari, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonhapus)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputharga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputstok, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttontambah)
                    .addComponent(buttonbatal))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonhapus))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputjudulActionPerformed

    private void inputhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputhargaActionPerformed

    private void inputpenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputpenulisActionPerformed

    private void inputstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputstokActionPerformed

    private void textcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcariActionPerformed

    private void buttonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhapusActionPerformed
        // TODO add your handling code here:
        if (inputjudul.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih buku yang akan di hapus");
        } else {
            int jawab = JOptionPane.showConfirmDialog(null, "Buku Ini akan dihapus, lanjutkan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
                    tokobuku = koneksi.createStatement();
                    String sql = "DELETE FROM data_buku WHERE judul = '" + inputjudul.getText() + "'";
                    tokobuku.executeUpdate(sql);

                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    kosong();
                    Tampilkanbuku();

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Buku Tidak Dapat Dihapus" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonhapusActionPerformed

    private void buttontambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontambahActionPerformed
        // TODO add your handling code here:
        try {
            // simpan data
            tokobuku = koneksi.createStatement();
            if (inputjudul.getText().equals("")
                || inputpenulis.getText().equals("")
                || inputharga.getText().equals("")
                || inputstok.getText().equals("")
                ) {
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Validasi data", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            
            if (buttontambah.getText() == "Tambah") {
                String cek = "SELECT * FROM data_buku WHERE judul = '" + inputjudul.getText() + "'";
                databuku = tokobuku.executeQuery(cek);
                if (databuku.next()) {
                    JOptionPane.showMessageDialog(null, "Upss.... ID ini Sudah Terdaftar");
                } else {
                    String judul = inputjudul.getText();
                    String penulis = inputpenulis.getText();
                    double harga = Double.parseDouble(inputharga.getText());
                    int stok = Integer.parseInt(inputstok.getText());

                    String sql = "INSERT INTO data_buku (judul, penulis, harga, stok) VALUES ('"
                        + judul + "', '"
                        + penulis + "', "
                        + harga + ", "
                        + stok + ")";
                    tokobuku.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Simpan Data Berhasil");
                    kosong();
                    Tampilkanbuku();
                }
            } else {
                //aksi ubah data
                String judul = inputjudul.getText();
                String penulis = inputpenulis.getText();
                double harga = Double.parseDouble(inputharga.getText());
                int stok = Integer.parseInt(inputstok.getText());
                    
               String sql = "UPDATE data_buku SET penulis = '" + penulis + "', harga = "
                + harga + ", stok = "
                + stok + " WHERE judul = '"
                + judul + "'";

                // Eksekusi query
                int rowsUpdated = tokobuku.executeUpdate(sql);
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
                } else {
                    JOptionPane.showMessageDialog(null, "Judul Buku tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
                }
                

                kosong();
                Tampilkanbuku();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tambah Buku Gagal " + e.getMessage());
        }
    }//GEN-LAST:event_buttontambahActionPerformed

    private void formAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Tampilkanbuku();
    }//GEN-LAST:event_formWindowOpened

    private void tabelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbukuMouseClicked
        // TODO add your handling code here:
        inputjudul.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 0).toString());
        inputpenulis.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 1).toString());
        inputharga.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 2).toString());
        inputstok.setText(tabelbuku.getValueAt(tabelbuku.getSelectedRow(), 3).toString());

        buttontambah.setText("Edit");
    }//GEN-LAST:event_tabelbukuMouseClicked

    private void textcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textcariKeyPressed
        // TODO add your handling code here:
        Caribuku();
    }//GEN-LAST:event_textcariKeyPressed

    private void buttonbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbatalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_buttonbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfacebuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfacebuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfacebuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfacebuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfacebuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonbatal;
    private javax.swing.JButton buttonhapus;
    private javax.swing.JButton buttontambah;
    private javax.swing.JTextField inputharga;
    private javax.swing.JTextField inputjudul;
    private javax.swing.JTextField inputpenulis;
    private javax.swing.JTextField inputstok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelbuku;
    private javax.swing.JTextField textcari;
    // End of variables declaration//GEN-END:variables
}
